/*
*	Copyright 2014 by Winpower Optronics Inc. All rights reserved.
*	$Id$
*/

#include "com_global_type.h"
#include "flash_para.h"
//#include "flash_para_S3.h"
//#include "SensorDefine.h"
//#include "SensorDefine_SUO47.h"
//#include "SensorDefine_E28.h"
//#include "SensorDefine_ols14x8.h"
//#include "SensorDefine_ols14x8_so_05_3.h"
#include "SensorDefine_h_worm.h"

#if ( (CHIPCONFIG_VER < 275) || (!defined(CHIPCONFIG_VER)) )
#error ============================================ ERROR!!! SensorDefine format is too OLD!! Please use ChipConfig Ver.273+. =====================================================================================
#endif


//0x4CE0
HW_PARAMETER HwSetting __attribute__ ((section(".hwsetting"))) =
{
	SERIAL_NO,
	PROJECT_VID,
	PROJECT_PID,
	UART_BAUDRATE,
	SELF_TARGET_RAW_MIN,
	SELF_TARGET_RAW_MAX,
	MUTU_TARGET_RAW_MIN,
	SELF_PULSE_COUNT,
	MUTU_PULSE_COUNT,	
	REPORT_RATE,
	PROTOCOL_VER,
	PROJECT_ID,
	HW_VER,
	FW_VER,
	I2C_ENABLEALLBIT,
	SELF_CC_CLOCK,
	SELF_CFB,
	SELF_PULSE_LENGTH,
	MUTU_CC_CLOCK,
	MUTU_CFB,
	MUTU_PULSE_LENGTH,
	MUTUAL_AUTOCC_START,
	SELF___AUTOCC_START,
	CPUMP,
	SELECT_CVDDH,
	SELF_FORCE_VDDA,
	PUMP_MODE_B_18V,
	TIMER0,
	OPEN_SHORT_CC_CLOCK,
	OPEN_SHORT_CFB,
	OPEN_SHORT_PULSE_LEN,
	OPEN_SHORT_PULSE_COUNT,
};


//0x4D20
SENSOR_DEFINE SensorDefine __attribute__ ((section(".sensorsetting"))) =
{
	SELF_PASSES,
	CFGMEM_SELF_RX_EN_TABLE,
	EFFECTIVE_SIZE_OF_CFGMEM_SELF_RX_EN_TABLE,
	FW_SELF_RAW_OFFSET_TABLE,
	EFFECTIVE_SIZE_OF_FW_SELF_RAW_OFFSET_TABLE,
	FW_SELF_RAW_OFFSET_LIST_PER_PASS,
	MUTUAL_PASSES,
	CFGMEM_MUTUAL_RX_EN_TABLE,
	EFFECTIVE_SIZE_OF_CFGMEM_MUTUAL_RX_EN_TABLE,
	REG54_MUTUAL_HORIZONTAL_RAW_OFFSET_TABLE,
	EFFECTIVE_SIZE_OF_REG54_MUTUAL_HORIZONTAL_RAW_OFFSET_TABLE,
	FW_MUTUAL_HORIZONTAL_ASCENDING_RAW_OFFSET_TABLE,
	EFFECTIVE_SIZE_OF_FW_MUTUAL_HORIZONTAL_ASCENDING_RAW_OFFSET_TABLE,
	FW_MUTUAL_RXS_PER_PASS_TABLE,
	TX_MODULATION,
	REG_C7_2,
	TOTAL_MODULATION_TX_SEQUENCE,
	CFGMEM_MUTUAL_TX_EN_TABLE,
	EFFECTIVE_SIZE_OF_CFGMEM_MUTUAL_TX_EN_TABLE,
	REG53_MUTUAL_VERTICAL_ROW_ID_TABLE,
	EFFECTIVE_SIZE_OF_REG53_MUTUAL_VERTICAL_ROW_ID_TABLE,
	I2C_SLAVE_ADDRESS,
	MUTUAL_TX_NUMBERS,
	MUTUAL_RX_NUMBERS,
	KEY_NUMBERS,
	KEY_TYPE,
	KEY0_TX,
	KEY0_RX,
	KEY1_TX,
	KEY1_RX,
	KEY2_TX,
	KEY2_RX,
	KEY3_TX,
	KEY3_RX,
};


//0x4EE0
FW_PARAMETER FwSetting __attribute__ ((section(".fwsetting"))) =
{ 
	SELF_TX_PEAK_THR,
	SELF_RX_PEAK_THR,
	MUTUAL_BASE_TRACE_UPPERBOUND,
	MUTUAL_BASE_TRACE_LOWERBOUND,
	SELF_FINGER_THR,
	MUTUAL_FINGER_THR,
	SELF_FINGER_FIRST_TOUCH,
	MUTUAL_FINGER_FIRST_TOUCH,
	TX_INTERPOLATION_VALUE,
	RX_INTERPOLATION_VALUE,
	PALM_OVERNODE,	
	MUTUAL_ENCLOSURE,
	MUTUAL_PALM_TH,
	MIN_MERGE_DISTANCE,
	POSITION_REMAPPING,
	TX_TARGET_RESOLUTION,
	RX_TARGET_RESOLUTION,
	TAPPING_DISTANCE,
	IDLE_MODE_TIME_TO_ENTER,
	JITTER_RANGE,
	TX_EDGE_START_SHORTAGE,
	TX_EDGE_END___SHORTAGE,
	RX_EDGE_START_SHORTAGE,
	RX_EDGE_END___SHORTAGE,
	AUTO_FREQ_SWITCHING_LEVEL,
	AUTO_FREQ_SELECTION_TABLE,
	STEPLESS_FAST_FILTER,
	STEPLESS_SLOW_FILTER,
	SELF_TX_NEGATIVE_THR,
	SELF_RX_NEGATIVE_THR,
	KEY_THRESHOLD,
	LCM_DIFF_HI,
	LCM_DIFF_LO,
	LCM_ABS_HI,
	LCM_ABS_LO,
	MUTUAL_ONLY_POF_THR,
	SELF_BASE_TRACE_STEP,
	SELF_BASE_TRACE_QUICK,
	MUTUAL_BASE_TRACE_STEP,
	ROTATE_QUEUE_LATENCY,
	PALM_TX_RANGE,
	PALM_RX_RANGE,
	AREA_MERGE_RATIO_BIT,
	KEY_DEBOUNCE,
	KEY_BASE_TRACE_STEP,
	SELF_ASSISTANCE,
	IDLE_MODE_SLP2_FRAME,
	TX_EDGE_EXTEND,
	RX_EDGE_EXTEND,
	DE_COMMON_MODE_NOISE,
	AUTO_FREQ_SEARCH_SPECTRUM,
	MANUAL_FORCE_MUTUAL_CC,
	MAMUAL_FORCE_SELF___CC,
	GESTURE_STYLE,
	GESTURE_DATA_LEN,
	BIG_THUMB_NODE_THR,
	SELF_TX_NEGATIVE_NODE,
	SELF_RX_NEGATIVE_NODE,
	POWER_ON_FINGER_DEBOUNCE_TIME,
	MUTUAL_ONLY_POF_ABNORMAL_FRAME,
};

//--- RAM area.
tParamAddresses ParamAddresses =
{
		(U16)&SensorDefine.Mutual_CFGMEM_RxEn_Table,
		(U16)&SensorDefine.Mutual_REG54_Horizontal_Offset_Table,
		(U16)&SensorDefine.Mutual_REG53_Vertical_ID_Table,
		(U16)&SensorDefine.Self_CFGMEM_RxEn_Table,
		(U16)&SensorDefine.Self_RawOffset_Table,
		CFGMEM_MUTUAL_RXEN_LENGTH,
		MUTUAL_REG54_LENGTH,
		MUTUAL_VERTICAL_ID_LENGTH,
		CFGMEM_SELF_RXEN_LENGTH,
		CFGMEM_SELF_RAWOFFSET_LENGTH,
		TX_MODULATION,
};
